name: make-linter

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make lint
